server:
  port: ${PORT:8081}
  servlet:
    context-path: "/api"
spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:testeFiapNaoFacaIssoEmPrd}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    aws:
      credentials:
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      sqs:
        endpoint: ${AWS_SQS_ENDPOINT}
queue:
  retorno-pagamento: ${QUEUE_RETORNO_PAGAMENTO}
  pedido-gerado: ${QUEUE_PEDIDO_GERADO}
