FROM openjdk:17

EXPOSE 8080

ENV POSTGRES_DB=postgres
ENV POSTGRES_HOST=database
ENV POSTGRES_PORT=5432
ENV POSTGRES_USERNAME=postgres
ENV POSTGRES_PASSWORD=testeFiapNaoFacaIssoEmPrd
ENV AWS_ACCESS_KEY=accessKey
ENV AWS_SECRET_KEY=secretKey
ENV AWS_REGION=us-east-1
ENV AWS_SQS_ENDPOINT=url

WORKDIR /app

COPY pagamento-valhalla-kitchen-1.0.jar app.jar

CMD ["java", "-jar", "app.jar"]