FROM postgres:latest

EXPOSE 5432

ENV POSTGRES_DB=postgres
ENV POSTGRES_HOST=database
ENV POSTGRES_PORT=5432
ENV POSTGRES_USERNAME=postgres
ENV POSTGRES_PASSWORD=testeFiapNaoFacaIssoEmPrd

COPY data /docker-entrypoint-initdb.d/
