FROM openjdk:17

EXPOSE 8081

ENV POSTGRES_DB=postgres
ENV POSTGRES_HOST=database
ENV POSTGRES_PORT=5431
ENV POSTGRES_USERNAME=postgres
ENV POSTGRES_PASSWORD=testeFiapNaoFacaIssoEmPrd

WORKDIR /app

COPY pagamento-valhalla-kitchen-1.0.jar app.jar

CMD ["java", "-jar", "app.jar"]